### ISSUE TITLE
后台是不是卡住了，不管聊天框发什么都没单应

### ISSUE THREAD

**Issue by sitsTi** [M3chD09/StickerNinjaBot#2]

**Comment by M3chD09** [comment]
你好，之前机器人部署在Heroku平台上，由于使用的是免费套餐，资源有限，当使用ffmpeg转换时可能会卡死。现在Heroku没有免费套餐了，我已经将机器人迁移到自己的VPS上，也许会有所改善。  
如使用时遇到问题，请提供你操作的详细流程，如使用了什么指令，打算转换的表情包的分享链接等等，以便于复现和排查。
